import type { Tour } from 'nextstepjs';

// ==========================================
// TOUR STEPS — LENGKAP
// Copy: Bahasa Indonesia, Gojek-style friendly
// Form labels: tetap Bahasa Inggris
// ==========================================

export const TOUR_STEPS: Tour[] = [

  // ════════════════════════════════════════
  // TOUR 1: ONBOARDING — Dashboard
  // Floating, tanpa selector
  // ════════════════════════════════════════
  {
    tour: 'onboarding',
    steps: [
      {
        icon: '👋',
        title: 'Halo, selamat datang!',
        content: 'Ini dashboard toko kamu. Dari sini kamu bisa pantau semua aktivitas tokomu dalam satu tempat.',
        side: 'bottom',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '🏪',
        title: 'Lengkapi profil toko',
        content: 'Mulai dari logo, foto hero, sampai info kontak — biar toko kamu makin profesional di mata pembeli.',
        side: 'bottom',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '📦',
        title: 'Tambah produk kamu',
        content: 'Upload foto, tulis deskripsi, dan tentukan harga. Gampang banget!',
        side: 'bottom',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '🎉',
        title: 'Siap berjualan!',
        content: 'Toko kamu udah bisa dikunjungi. Yuk mulai lengkapi semuanya biar makin oke!',
        side: 'bottom',
        showControls: true,
        showSkip: false,
      },
    ],
  },

  // ════════════════════════════════════════
  // TOUR 2: TOKO — /settings/toko
  // 26 steps — semua field semua tab
  // ════════════════════════════════════════
  {
    tour: 'toko',
    steps: [
      // ── Hero: Brand Identity (0-2) ──────
      {
        icon: '🖼️',
        title: 'Upload logo toko kamu',
        content: 'Logo muncul di header toko, halaman produk, sampai hasil pencarian Google. Pakai PNG transparan biar keliatan bagus di semua background!',
        selector: '#tour-logo-upload',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '🏷️',
        title: 'Nama toko kamu',
        content: 'Nama ini muncul di halaman utama toko, hasil pencarian, dan notifikasi WhatsApp ke pembeli. Pastiin udah sesuai brand kamu ya!',
        selector: '#tour-store-name',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🗂️',
        title: 'Kategori toko kamu',
        content: 'Ini yang bikin toko kamu muncul di halaman Discover sesuai kategorinya. Pembeli yang nyari produk di kategori ini bisa langsung nemuin toko kamu! Kategori tidak bisa diubah ya.',
        selector: '#tour-category',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      // ── Hero: Brand Story (3-5) ─────────
      {
        icon: '✍️',
        title: 'Headline toko kamu',
        content: 'Kalimat pertama yang dilihat pembeli saat buka toko kamu. Bikin yang singkat, kuat, dan langsung nangkep! Contoh: "Kopi Specialty Terbaik di Kota".',
        selector: '#tour-hero-headline',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '💬',
        title: 'Subheading toko kamu',
        content: 'Satu kalimat yang menjelaskan nilai utama toko kamu. Muncul tepat di bawah headline. Contoh: "Dikirim dalam 30 menit, dijamin segar."',
        selector: '#tour-hero-subheading',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📌',
        title: 'Store Tagline',
        content: 'Tagline pendek yang muncul di profil toko dan hasil pencarian. Ini yang bikin orang ingat sama brand kamu. Contoh: "Premium burgers, authentic Asian fusion flavors."',
        selector: '#tour-store-tagline',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      // ── Hero: Appearance (6-8) ──────────
      {
        icon: '🎨',
        title: 'Warna brand kamu',
        content: 'Warna ini jadi aksen utama di tombol, link, dan elemen penting toko kamu. Pilih yang paling cocok sama identitas brand!',
        selector: '#tour-brand-color',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '🌅',
        title: 'Background image hero',
        content: 'Foto besar yang jadi latar halaman utama toko kamu. Ini kesan pertama pembeli! Gunakan foto produk terbaik atau suasana toko yang menarik.',
        selector: '#tour-hero-bg',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '🔘',
        title: 'Teks tombol CTA hero',
        content: 'Teks di tombol utama halaman toko kamu. Muncul di atas background image. Singkat dan action-oriented ya! Contoh: "Order Now", "Shop Now".',
        selector: '#tour-cta-button-label',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      // ── About (9-13) ────────────────────
      {
        icon: '📖',
        title: 'Judul section About',
        content: 'Judul ini muncul di bagian "Tentang Kami" halaman toko. Bikin yang bikin penasaran! Contoh: "The Story Behind Every Bite".',
        selector: '#tour-about-title',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📝',
        title: 'Subheading section About',
        content: 'Kalimat pendukung di bawah judul About. Kasih konteks yang menarik. Contoh: "Dibuat dengan cinta sejak 2019."',
        selector: '#tour-about-subtitle',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📜',
        title: 'Cerita toko kamu',
        content: 'Ceritakan tentang brand kamu — siapa kamu, apa yang kamu jual, dan kenapa pembeli harus pilih kamu. Ideal 150–300 kata. Makin personal makin bagus!',
        selector: '#tour-about-story',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🖼️',
        title: 'Foto section About',
        content: 'Foto yang muncul di sebelah cerita toko kamu. Bisa foto dapur, tim, atau produk unggulan. Bikin makin personal dan terpercaya!',
        selector: '#tour-about-image',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '⭐',
        title: 'Key Highlights toko kamu',
        content: 'Keunggulan utama yang tampil sebagai ikon di section About. Contoh: "Pengiriman Cepat", "Bahan Segar", "Sudah 500+ Pelanggan". Makin banyak, makin meyakinkan!',
        selector: '#tour-about-highlights',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      // ── Testimonials (14-16) ────────────
      {
        icon: '💬',
        title: 'Judul section Testimonials',
        content: 'Judul yang muncul di atas deretan testimoni pembeli. Bikin yang emosional! Contoh: "Ribuan Pelanggan Sudah Puas".',
        selector: '#tour-testimonials-title',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '✨',
        title: 'Subheading Testimonials',
        content: 'Kalimat pendukung di bawah judul testimoni. Contoh: "Cerita nyata dari pelanggan setia kami."',
        selector: '#tour-testimonials-subtitle',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🌟',
        title: 'Tambah testimoni pembeli',
        content: 'Testimoni adalah social proof paling powerful! Minta review dari pelanggan puas dan tambahin di sini. Minimal 3 testimoni sudah cukup untuk membangun kepercayaan.',
        selector: '#tour-add-testimonial',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      // ── Contact (17-21) ─────────────────
      {
        icon: '📞',
        title: 'Judul section Contact',
        content: 'Judul yang muncul di halaman kontak toko kamu. Contoh: "Hubungi Kami" atau "Ada Pertanyaan?".',
        selector: '#tour-contact-title',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '💚',
        title: 'Nomor WhatsApp kamu',
        content: 'Ini yang paling penting! Saat pembeli klik tombol WhatsApp di toko, mereka langsung diarahkan ke nomor ini. Format: 628xxxxxxxxxx (tanpa tanda +).',
        selector: '#tour-whatsapp',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📱',
        title: 'Nomor telepon',
        content: 'Nomor telepon alternatif yang tampil di halaman kontak. Opsional, tapi bagus untuk toko yang punya hotline atau telepon kantor.',
        selector: '#tour-phone',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📍',
        title: 'Alamat toko kamu',
        content: 'Alamat lengkap yang muncul di halaman kontak. Penting untuk toko fisik atau yang menerima kunjungan langsung dari pelanggan.',
        selector: '#tour-address',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🗺️',
        title: 'Google Maps embed',
        content: 'Embed peta langsung di halaman toko! Caranya: buka Google Maps → cari lokasi toko → klik Share → Embed a map → copy URL dari src="...".',
        selector: '#tour-maps-url',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      // ── CTA (22-25) ─────────────────────
      {
        icon: '🚀',
        title: 'Headline Call to Action',
        content: 'Judul besar di section CTA — biasanya di bagian bawah toko. Last impression pembeli! Contoh: "Siap Order Sekarang?".',
        selector: '#tour-cta-title',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '💡',
        title: 'Supporting text CTA',
        content: 'Kalimat pendukung di bawah headline CTA. Perkuat alasan pembeli untuk action. Contoh: "Ribuan pelanggan sudah puas. Giliran kamu!".',
        selector: '#tour-cta-subtitle',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🔘',
        title: 'Teks tombol CTA',
        content: 'Teks di tombol utama section CTA. Singkat dan langsung ke action! Contoh: "Pesan Sekarang", "Lihat Produk".',
        selector: '#tour-cta-button',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🔗',
        title: 'Link tombol CTA',
        content: 'Saat pembeli klik tombol CTA, mereka diarahkan ke link ini. Bisa internal seperti /products, atau eksternal ke WhatsApp, marketplace, dll.',
        selector: '#tour-cta-link',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },

  // ════════════════════════════════════════
  // TOUR 3: CHANNELS — /settings/channels
  // 10 steps
  // ════════════════════════════════════════
  {
    tour: 'channels',
    steps: [
      // ── SEO (0-2) ───────────────────────
      {
        icon: '🔍',
        title: 'Meta Title toko kamu',
        content: 'Ini judul yang muncul di hasil pencarian Google! Ideal 50–60 karakter. Contoh: "Coffe House - Kopi Specialty Terbaik Jakarta".',
        selector: '#tour-meta-title',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📄',
        title: 'Meta Description',
        content: 'Deskripsi singkat yang muncul di bawah judul di Google. Ideal 120–160 karakter. Ini yang bikin orang mau klik toko kamu di hasil pencarian!',
        selector: '#tour-meta-description',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📱',
        title: 'Social media links',
        content: 'Link akun sosmed kamu yang muncul di footer toko. Makin banyak platform aktif, makin terpercaya toko kamu di mata pembeli!',
        selector: '#tour-social-links',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      // ── Pembayaran (3-6) ────────────────
      {
        icon: '💱',
        title: 'Mata uang toko kamu',
        content: 'Semua harga produk akan ditampilkan dalam mata uang ini. Pilih sesuai lokasi dan target pasar kamu!',
        selector: '#tour-currency',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🏦',
        title: 'Rekening bank kamu',
        content: 'Pembeli yang pilih transfer bank akan diarahkan ke rekening ini. Tambah minimal 1 rekening biar toko kamu bisa menerima pembayaran!',
        selector: '#tour-add-bank',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '💳',
        title: 'E-wallet kamu',
        content: 'Semakin banyak metode pembayaran, semakin besar peluang pembeli jadi beli! Tambah GoPay, OVO, DANA, atau e-wallet lainnya.',
        selector: '#tour-add-ewallet',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🏠',
        title: 'Cash on Delivery (COD)',
        content: 'COD bisa ningkatin konversi secara signifikan — terutama untuk pembeli yang belum percaya belanja online. Aktifkan kalau kamu siap layani COD!',
        selector: '#tour-cod',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      // ── Pengiriman (7-9) ────────────────
      {
        icon: '🚚',
        title: 'Kurir pengiriman',
        content: 'Aktifkan kurir yang kamu gunakan. Ini yang ditampilkan ke pembeli saat checkout. Semakin banyak pilihan kurir, semakin fleksibel!',
        selector: '#tour-carriers',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '🎁',
        title: 'Gratis ongkir threshold',
        content: 'Tentukan minimum belanja untuk dapat gratis ongkir. Taktik ampuh buat ningkatin nilai order! Contoh: gratis ongkir di atas Rp 100.000.',
        selector: '#tour-free-shipping',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '💰',
        title: 'Biaya pengiriman default',
        content: 'Ongkos kirim flat untuk pembeli yang belum mencapai threshold gratis ongkir. Sesuaikan dengan rata-rata ongkir kurir yang kamu pakai!',
        selector: '#tour-flat-rate',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },

  // ════════════════════════════════════════
  // TOUR 4: PRODUCTS NEW
  // ════════════════════════════════════════
  {
    tour: 'products_new',
    steps: [
      {
        icon: '✏️',
        title: 'Nama produk yang jelas',
        content: 'Tulis nama yang spesifik dan mudah dicari. "Kaos Polos Oversize Hitam" jauh lebih bagus dari cuma "Kaos". Nama ini muncul di halaman produk dan hasil pencarian.',
        selector: '#tour-product-name',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📝',
        title: 'Deskripsi produk',
        content: 'Jelaskan produkmu sejelas mungkin — bahan, ukuran, warna, cara pakai, dll. Deskripsi yang lengkap = lebih sedikit pertanyaan dari pembeli!',
        selector: '#tour-product-description',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🗂️',
        title: 'Kategori produk',
        content: 'Kategori membantu pembeli filter produk di toko kamu. Kalau belum ada yang pas, ketik nama kategori baru langsung di sini!',
        selector: '#tour-product-category',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📸',
        title: 'Foto produk yang menarik',
        content: 'Foto adalah senjata utama kamu! Upload minimal 1 foto dengan pencahayaan yang bagus. Foto dari berbagai sudut makin bagus. Ukuran ideal: minimal 800×800px.',
        selector: '#tour-product-image',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '💰',
        title: 'Harga jual produk',
        content: 'Harga ini yang dilihat dan dibayar pembeli. Muncul besar di halaman produk. Kalau ada harga coret (diskon), isi juga di "Compare Price" di bawahnya!',
        selector: '#tour-product-price',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📦',
        title: 'Stok produk',
        content: 'Isi jumlah stok yang tersedia. Kalau stok habis, produk otomatis ditandai "Stok Habis" di toko. Aktifkan Track Inventory biar stok ter-update otomatis!',
        selector: '#tour-product-stock',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '👁️',
        title: 'Status produk',
        content: 'Kalau aktif, produk langsung keliatan di toko. Kalau draft, hanya kamu yang bisa lihat. Gunakan draft kalau produk belum siap dijual.',
        selector: '#tour-product-status',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },

  // ════════════════════════════════════════
  // TOUR 5: PRODUCTS EDIT
  // ════════════════════════════════════════
  {
    tour: 'products_edit',
    steps: [
      {
        icon: '🔄',
        title: 'Edit nama produk',
        content: 'Perbarui nama produk kapan aja. Perubahan langsung terlihat di toko dan hasil pencarian.',
        selector: '#tour-product-name',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📸',
        title: 'Perbarui foto produk',
        content: 'Foto baru bisa bikin produk terlihat lebih fresh. Upload foto yang lebih bagus kalau ada!',
        selector: '#tour-product-image',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '💰',
        title: 'Update harga',
        content: 'Pastiin harga selalu up-to-date. Kalau lagi ada promo, aktifkan harga coret di "Compare Price" biar keliatan ada diskon!',
        selector: '#tour-product-price',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📦',
        title: 'Update stok',
        content: 'Stok yang akurat = pembeli tidak kecewa! Selalu update stok setiap kali ada penjualan manual atau restock masuk.',
        selector: '#tour-product-stock',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
    ],
  },
];

// ════════════════════════════════════════
// TAB MAP
// step index → tab yang harus aktif
// ════════════════════════════════════════

export const TOKO_TAB_MAP: Record<number, string> = {
  0: 'hero-section', 1: 'hero-section', 2: 'hero-section',
  3: 'hero-section', 4: 'hero-section', 5: 'hero-section',
  6: 'hero-section', 7: 'hero-section', 8: 'hero-section',
  9: 'about', 10: 'about', 11: 'about', 12: 'about', 13: 'about',
  14: 'testimonials', 15: 'testimonials', 16: 'testimonials',
  17: 'contact', 18: 'contact', 19: 'contact', 20: 'contact', 21: 'contact',
  22: 'cta', 23: 'cta', 24: 'cta', 25: 'cta',
};

export const CHANNELS_TAB_MAP: Record<number, string> = {
  0: 'pencarian', 1: 'pencarian', 2: 'pencarian',
  3: 'pembayaran', 4: 'pembayaran', 5: 'pembayaran', 6: 'pembayaran',
  7: 'pengiriman', 8: 'pengiriman', 9: 'pengiriman',
};
