import {
  // Icons untuk kategori
  ShoppingCart,
  Wrench,
  Scissors,
  Shirt,
  UtensilsCrossed,
  Package,
  Coffee,
  Cake,
  Pill,
  Wind,
  Camera,
  Dog,
  Dumbbell,
  Home,
  Printer,
  Store,
  Hammer,
  Car,
  Bike,
  Droplet,
  Lightbulb,
  Lock,
  Paintbrush,
  Trees,
  Flower2,
  Sparkles,
  Sofa,
  Truck,
  Toilet,
  Stethoscope,
  Eye,
  Heart,
  Smile,
  Syringe,
  Plane,
  MapPin,
  PartyPopper,
  Church,
  ShoppingBag,
  BookOpen,
  Film,
  Music,
  Hotel,
  Map,
  CarFront,
  Waves,
  School,
  type LucideIcon,
} from 'lucide-react';

// ==========================================
// CATEGORY TYPES
// ==========================================

export interface CategoryFeatures {
  stock: boolean;
  debt: boolean;
  booking: boolean;
  tracking: boolean;
  membership: boolean;
  cashier: boolean;
}

export interface CategoryLabels {
  product: string;
  price: string;
  customer: string;
}

export interface CategoryConfig {
  key: string;
  icon: LucideIcon;
  label: string;
  labelShort: string;
  color: string;
  description: string;
  group: string;
  features: CategoryFeatures;
  labels: CategoryLabels;
}

export interface CategoryGroup {
  key: string;
  label: string;
  emoji: string;
  icon: LucideIcon;
  color: string;
  count: number;
}

// ==========================================
// 7 MAIN CATEGORY GROUPS
// ==========================================

export const CATEGORY_GROUPS: Record<string, CategoryGroup> = {
  KULINER: {
    key: 'KULINER',
    label: 'Kuliner',
    emoji: '🍽️',
    icon: UtensilsCrossed,
    color: '#f59e0b',
    count: 15,
  },
  RUMAH_TAMAN: {
    key: 'RUMAH_TAMAN',
    label: 'Rumah & Taman',
    emoji: '🏠',
    icon: Home,
    color: '#10b981',
    count: 15,
  },
  OTOMOTIF: {
    key: 'OTOMOTIF',
    label: 'Otomotif',
    emoji: '🚗',
    icon: Car,
    color: '#3b82f6',
    count: 12,
  },
  KESEHATAN_KECANTIKAN: {
    key: 'KESEHATAN_KECANTIKAN',
    label: 'Kesehatan & Kecantikan',
    emoji: '💆',
    icon: Heart,
    color: '#ec4899',
    count: 12,
  },
  TRAVEL_HIBURAN: {
    key: 'TRAVEL_HIBURAN',
    label: 'Travel & Hiburan',
    emoji: '✈️',
    icon: Plane,
    color: '#8b5cf6',
    count: 14,
  },
  BELANJA: {
    key: 'BELANJA',
    label: 'Belanja',
    emoji: '🛍️',
    icon: ShoppingBag,
    color: '#06b6d4',
    count: 12,
  },
  LAINNYA: {
    key: 'LAINNYA',
    label: 'Lainnya',
    emoji: '📦',
    icon: Package,
    color: '#6b7280',
    count: 14,
  },
};

// ==========================================
// 94 CATEGORIES (Grouped by 7 main groups)
// ==========================================

export const CATEGORY_CONFIG: Record<string, CategoryConfig> = {
  // ========================================
  // 🍽️ KULINER (15)
  // ========================================
  RESTORAN: {
    key: 'RESTORAN',
    icon: UtensilsCrossed,
    label: 'Restoran',
    labelShort: 'Restoran',
    color: '#f59e0b',
    description: 'Restoran, rumah makan',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: true, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  WARUNG: {
    key: 'WARUNG',
    icon: Store,
    label: 'Warung',
    labelShort: 'Warung',
    color: '#10b981',
    description: 'Warung makan, warteg',
    group: 'KULINER',
    features: { stock: true, debt: true, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  CAFE: {
    key: 'CAFE',
    icon: Coffee,
    label: 'Cafe',
    labelShort: 'Cafe',
    color: '#78350f',
    description: 'Cafe, coffee shop',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: true, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  DELIVERY: {
    key: 'DELIVERY',
    icon: Bike,
    label: 'Delivery',
    labelShort: 'Delivery',
    color: '#ef4444',
    description: 'Layanan antar makanan',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: true, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  SARAPAN: {
    key: 'SARAPAN',
    icon: Coffee,
    label: 'Sarapan',
    labelShort: 'Sarapan',
    color: '#fbbf24',
    description: 'Warung sarapan pagi',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  BAKERY: {
    key: 'BAKERY',
    icon: Cake,
    label: 'Bakery',
    labelShort: 'Bakery',
    color: '#f97316',
    description: 'Toko roti, bakery',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: true, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  FOOD_TRUCK: {
    key: 'FOOD_TRUCK',
    icon: Truck,
    label: 'Food Truck',
    labelShort: 'Food Truck',
    color: '#dc2626',
    description: 'Gerobak makanan keliling',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  SEAFOOD: {
    key: 'SEAFOOD',
    icon: UtensilsCrossed,
    label: 'Seafood',
    labelShort: 'Seafood',
    color: '#0ea5e9',
    description: 'Restoran seafood',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: true, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  AYAM_GORENG: {
    key: 'AYAM_GORENG',
    icon: UtensilsCrossed,
    label: 'Ayam Goreng',
    labelShort: 'Ayam Goreng',
    color: '#ea580c',
    description: 'Warung ayam goreng',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  MIE_BAKSO: {
    key: 'MIE_BAKSO',
    icon: UtensilsCrossed,
    label: 'Mie & Bakso',
    labelShort: 'Mie Bakso',
    color: '#d97706',
    description: 'Warung mie, bakso',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  PADANG: {
    key: 'PADANG',
    icon: UtensilsCrossed,
    label: 'Masakan Padang',
    labelShort: 'Padang',
    color: '#dc2626',
    description: 'Rumah makan Padang',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  JAWA: {
    key: 'JAWA',
    icon: UtensilsCrossed,
    label: 'Masakan Jawa',
    labelShort: 'Jawa',
    color: '#16a34a',
    description: 'Rumah makan Jawa',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  SUNDA: {
    key: 'SUNDA',
    icon: UtensilsCrossed,
    label: 'Masakan Sunda',
    labelShort: 'Sunda',
    color: '#15803d',
    description: 'Rumah makan Sunda',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  DESSERT: {
    key: 'DESSERT',
    icon: Cake,
    label: 'Dessert',
    labelShort: 'Dessert',
    color: '#db2777',
    description: 'Es krim, minuman, dessert',
    group: 'KULINER',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },
  CATERING: {
    key: 'CATERING',
    icon: UtensilsCrossed,
    label: 'Catering',
    labelShort: 'Catering',
    color: '#f59e0b',
    description: 'Catering harian, prasmanan, nasi box',
    group: 'KULINER',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Menu', price: 'Harga', customer: 'Pelanggan' },
  },

  // ========================================
  // 🏠 RUMAH & TAMAN (15)
  // ========================================
  KONTRAKTOR: {
    key: 'KONTRAKTOR',
    icon: Hammer,
    label: 'Kontraktor',
    labelShort: 'Kontraktor',
    color: '#f59e0b',
    description: 'Jasa kontraktor bangunan',
    group: 'RUMAH_TAMAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Proyek', price: 'Harga', customer: 'Klien' },
  },
  TUKANG_LEDENG: {
    key: 'TUKANG_LEDENG',
    icon: Droplet,
    label: 'Tukang Ledeng',
    labelShort: 'Ledeng',
    color: '#0ea5e9',
    description: 'Service pipa, kran, toilet',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  TUKANG_LISTRIK: {
    key: 'TUKANG_LISTRIK',
    icon: Lightbulb,
    label: 'Tukang Listrik',
    labelShort: 'Listrik',
    color: '#fbbf24',
    description: 'Instalasi listrik, service',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  SERVICE_AC: {
    key: 'SERVICE_AC',
    icon: Wind,
    label: 'Service AC',
    labelShort: 'AC',
    color: '#06b6d4',
    description: 'Service AC, elektronik, kulkas',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  ELEKTRONIK: {
    key: 'ELEKTRONIK',
    icon: Lightbulb,
    label: 'Service Elektronik',
    labelShort: 'Elektronik',
    color: '#3b82f6',
    description: 'Service TV, kulkas, mesin cuci',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  ATAP: {
    key: 'ATAP',
    icon: Home,
    label: 'Tukang Atap',
    labelShort: 'Atap',
    color: '#ef4444',
    description: 'Pasang atap, renovasi',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  TUKANG_KUNCI: {
    key: 'TUKANG_KUNCI',
    icon: Lock,
    label: 'Tukang Kunci',
    labelShort: 'Kunci',
    color: '#6b7280',
    description: 'Duplikat kunci, ganti kunci',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  TUKANG_CAT: {
    key: 'TUKANG_CAT',
    icon: Paintbrush,
    label: 'Tukang Cat',
    labelShort: 'Cat',
    color: '#8b5cf6',
    description: 'Pengecatan rumah, tembok',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  LANDSCAPE: {
    key: 'LANDSCAPE',
    icon: Trees,
    label: 'Landscape',
    labelShort: 'Landscape',
    color: '#10b981',
    description: 'Taman, landscape',
    group: 'RUMAH_TAMAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Proyek', price: 'Harga', customer: 'Klien' },
  },
  TOKO_TANAMAN: {
    key: 'TOKO_TANAMAN',
    icon: Trees,
    label: 'Toko Tanaman',
    labelShort: 'Tanaman',
    color: '#16a34a',
    description: 'Tanaman hias, pot',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  FLORIST: {
    key: 'FLORIST',
    icon: Flower2,
    label: 'Florist',
    labelShort: 'Florist',
    color: '#ec4899',
    description: 'Toko bunga, rangkaian',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: false, booking: true, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  CLEANING_SERVICE: {
    key: 'CLEANING_SERVICE',
    icon: Sparkles,
    label: 'Cleaning Service',
    labelShort: 'Cleaning',
    color: '#3b82f6',
    description: 'Jasa bersih rumah, kantor',
    group: 'RUMAH_TAMAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: true, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  FURNITURE: {
    key: 'FURNITURE',
    icon: Sofa,
    label: 'Furniture',
    labelShort: 'Furniture',
    color: '#92400e',
    description: 'Toko furniture, mebel',
    group: 'RUMAH_TAMAN',
    features: { stock: true, debt: true, booking: true, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  PINDAHAN: {
    key: 'PINDAHAN',
    icon: Truck,
    label: 'Jasa Pindahan',
    labelShort: 'Pindahan',
    color: '#f59e0b',
    description: 'Jasa pindahan, angkut barang',
    group: 'RUMAH_TAMAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  SEDOT_WC: {
    key: 'SEDOT_WC',
    icon: Toilet,
    label: 'Sedot WC',
    labelShort: 'Sedot WC',
    color: '#06b6d4',
    description: 'Sedot WC, septic tank',
    group: 'RUMAH_TAMAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },

  // ========================================
  // 🚗 OTOMOTIF (12)
  // ========================================
  BENGKEL_MOBIL: {
    key: 'BENGKEL_MOBIL',
    icon: Car,
    label: 'Bengkel Mobil',
    labelShort: 'Bengkel Mobil',
    color: '#ef4444',
    description: 'Service mobil, tune up',
    group: 'OTOMOTIF',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  BENGKEL_MOTOR: {
    key: 'BENGKEL_MOTOR',
    icon: Bike,
    label: 'Bengkel Motor',
    labelShort: 'Bengkel Motor',
    color: '#f97316',
    description: 'Service motor, ganti oli, tune up',
    group: 'OTOMOTIF',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  BODY_REPAIR: {
    key: 'BODY_REPAIR',
    icon: Wrench,
    label: 'Body Repair',
    labelShort: 'Body Repair',
    color: '#dc2626',
    description: 'Bengkel body, cat mobil',
    group: 'OTOMOTIF',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  GANTI_OLI: {
    key: 'GANTI_OLI',
    icon: Droplet,
    label: 'Ganti Oli',
    labelShort: 'Ganti Oli',
    color: '#ea580c',
    description: 'Service ganti oli cepat',
    group: 'OTOMOTIF',
    features: { stock: true, debt: false, booking: false, tracking: true, membership: true, cashier: true },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  BAN_VELG: {
    key: 'BAN_VELG',
    icon: Car,
    label: 'Ban & Velg',
    labelShort: 'Ban Velg',
    color: '#374151',
    description: 'Toko ban, velg, spooring',
    group: 'OTOMOTIF',
    features: { stock: true, debt: true, booking: true, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  TOWING: {
    key: 'TOWING',
    icon: Truck,
    label: 'Towing',
    labelShort: 'Towing',
    color: '#fbbf24',
    description: 'Jasa derek mobil, motor',
    group: 'OTOMOTIF',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  CUCI_MOBIL: {
    key: 'CUCI_MOBIL',
    icon: Droplet,
    label: 'Cuci Mobil',
    labelShort: 'Cuci Mobil',
    color: '#0ea5e9',
    description: 'Cuci mobil, motor',
    group: 'OTOMOTIF',
    features: { stock: false, debt: false, booking: false, tracking: false, membership: true, cashier: true },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  SALON_MOBIL: {
    key: 'SALON_MOBIL',
    icon: Sparkles,
    label: 'Salon Mobil',
    labelShort: 'Salon Mobil',
    color: '#3b82f6',
    description: 'Detailing, coating mobil',
    group: 'OTOMOTIF',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Paket', price: 'Harga', customer: 'Pelanggan' },
  },
  PARKIR: {
    key: 'PARKIR',
    icon: Car,
    label: 'Parkir',
    labelShort: 'Parkir',
    color: '#6b7280',
    description: 'Tempat parkir harian, bulanan',
    group: 'OTOMOTIF',
    features: { stock: false, debt: false, booking: false, tracking: false, membership: true, cashier: true },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  DEALER: {
    key: 'DEALER',
    icon: CarFront,
    label: 'Dealer',
    labelShort: 'Dealer',
    color: '#dc2626',
    description: 'Dealer mobil, motor',
    group: 'OTOMOTIF',
    features: { stock: true, debt: true, booking: true, tracking: true, membership: false, cashier: true },
    labels: { product: 'Unit', price: 'Harga', customer: 'Pelanggan' },
  },
  SPAREPART: {
    key: 'SPAREPART',
    icon: Wrench,
    label: 'Sparepart',
    labelShort: 'Sparepart',
    color: '#f97316',
    description: 'Toko sparepart mobil, motor',
    group: 'OTOMOTIF',
    features: { stock: true, debt: true, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  AKSESORIS: {
    key: 'AKSESORIS',
    icon: Store,
    label: 'Aksesoris',
    labelShort: 'Aksesoris',
    color: '#8b5cf6',
    description: 'Aksesoris mobil, motor',
    group: 'OTOMOTIF',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },

  // ========================================
  // 💆 KESEHATAN & KECANTIKAN (12)
  // ========================================
  DOKTER_GIGI: {
    key: 'DOKTER_GIGI',
    icon: Smile,
    label: 'Dokter Gigi',
    labelShort: 'Dokter Gigi',
    color: '#3b82f6',
    description: 'Klinik gigi, dental',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pasien' },
  },
  DOKTER: {
    key: 'DOKTER',
    icon: Stethoscope,
    label: 'Dokter',
    labelShort: 'Dokter',
    color: '#ef4444',
    description: 'Praktek dokter umum',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pasien' },
  },
  KLINIK: {
    key: 'KLINIK',
    icon: Heart,
    label: 'Klinik',
    labelShort: 'Klinik',
    color: '#dc2626',
    description: 'Klinik kesehatan',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pasien' },
  },
  APOTEK: {
    key: 'APOTEK',
    icon: Pill,
    label: 'Apotek',
    labelShort: 'Apotek',
    color: '#16a34a',
    description: 'Obat, vitamin, alat kesehatan',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Obat', price: 'Harga', customer: 'Pelanggan' },
  },
  OPTIK: {
    key: 'OPTIK',
    icon: Eye,
    label: 'Optik',
    labelShort: 'Optik',
    color: '#0ea5e9',
    description: 'Toko kacamata, softlens',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: true, debt: false, booking: true, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  PIJAT: {
    key: 'PIJAT',
    icon: Heart,
    label: 'Pijat',
    labelShort: 'Pijat',
    color: '#ec4899',
    description: 'Pijat, refleksi',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  SALON: {
    key: 'SALON',
    icon: Scissors,
    label: 'Salon',
    labelShort: 'Salon',
    color: '#db2777',
    description: 'Salon, barbershop',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Layanan', price: 'Harga', customer: 'Pelanggan' },
  },
  NAIL_ART: {
    key: 'NAIL_ART',
    icon: Sparkles,
    label: 'Nail Art',
    labelShort: 'Nail Art',
    color: '#f472b6',
    description: 'Salon kuku, nail art',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: true, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Layanan', price: 'Harga', customer: 'Pelanggan' },
  },
  BARBERSHOP: {
    key: 'BARBERSHOP',
    icon: Scissors,
    label: 'Barbershop',
    labelShort: 'Barbershop',
    color: '#374151',
    description: 'Barbershop pria',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Layanan', price: 'Harga', customer: 'Pelanggan' },
  },
  SPA: {
    key: 'SPA',
    icon: Sparkles,
    label: 'Spa',
    labelShort: 'Spa',
    color: '#a855f7',
    description: 'Spa, massage, treatment',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: true, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Paket', price: 'Harga', customer: 'Pelanggan' },
  },
  SKINCARE: {
    key: 'SKINCARE',
    icon: Heart,
    label: 'Skincare',
    labelShort: 'Skincare',
    color: '#ec4899',
    description: 'Klinik kecantikan, skincare',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: true, cashier: true },
    labels: { product: 'Treatment', price: 'Harga', customer: 'Pasien' },
  },
  FISIOTERAPI: {
    key: 'FISIOTERAPI',
    icon: Heart,
    label: 'Fisioterapi',
    labelShort: 'Fisioterapi',
    color: '#0891b2',
    description: 'Klinik fisioterapi',
    group: 'KESEHATAN_KECANTIKAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pasien' },
  },

  // ========================================
  // ✈️ TRAVEL & HIBURAN (14)
  // ========================================
  WISATA: {
    key: 'WISATA',
    icon: MapPin,
    label: 'Wisata',
    labelShort: 'Wisata',
    color: '#10b981',
    description: 'Tempat wisata, objek wisata',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: false, cashier: true },
    labels: { product: 'Tiket', price: 'Harga', customer: 'Pengunjung' },
  },
  PLAYGROUND: {
    key: 'PLAYGROUND',
    icon: PartyPopper,
    label: 'Playground',
    labelShort: 'Playground',
    color: '#f59e0b',
    description: 'Playground anak, arena bermain',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Tiket', price: 'Harga', customer: 'Pengunjung' },
  },
  VENUE: {
    key: 'VENUE',
    icon: PartyPopper,
    label: 'Venue',
    labelShort: 'Venue',
    color: '#8b5cf6',
    description: 'Venue acara, gedung pernikahan',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Paket', price: 'Harga', customer: 'Klien' },
  },
  TEMPAT_IBADAH: {
    key: 'TEMPAT_IBADAH',
    icon: Church,
    label: 'Tempat Ibadah',
    labelShort: 'Ibadah',
    color: '#6b7280',
    description: 'Masjid, gereja, vihara',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: false, tracking: false, membership: false, cashier: false },
    labels: { product: 'Info', price: '-', customer: 'Jemaah' },
  },
  MALL: {
    key: 'MALL',
    icon: ShoppingBag,
    label: 'Mall',
    labelShort: 'Mall',
    color: '#3b82f6',
    description: 'Mall, pusat perbelanjaan',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: false, tracking: false, membership: false, cashier: false },
    labels: { product: 'Tenant', price: '-', customer: 'Pengunjung' },
  },
  TOKO_BUKU: {
    key: 'TOKO_BUKU',
    icon: BookOpen,
    label: 'Toko Buku',
    labelShort: 'Toko Buku',
    color: '#f97316',
    description: 'Toko buku, alat tulis',
    group: 'TRAVEL_HIBURAN',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  BIOSKOP: {
    key: 'BIOSKOP',
    icon: Film,
    label: 'Bioskop',
    labelShort: 'Bioskop',
    color: '#dc2626',
    description: 'Bioskop, cinema',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Tiket', price: 'Harga', customer: 'Penonton' },
  },
  KARAOKE: {
    key: 'KARAOKE',
    icon: Music,
    label: 'Karaoke',
    labelShort: 'Karaoke',
    color: '#ec4899',
    description: 'Tempat karaoke',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Room', price: 'Harga', customer: 'Pengunjung' },
  },
  BOWLING: {
    key: 'BOWLING',
    icon: PartyPopper,
    label: 'Bowling',
    labelShort: 'Bowling',
    color: '#6366f1',
    description: 'Tempat bowling',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Lane', price: 'Harga', customer: 'Pengunjung' },
  },
  HOTEL: {
    key: 'HOTEL',
    icon: Hotel,
    label: 'Hotel',
    labelShort: 'Hotel',
    color: '#0891b2',
    description: 'Hotel, penginapan',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Kamar', price: 'Harga', customer: 'Tamu' },
  },
  TRAVEL: {
    key: 'TRAVEL',
    icon: Plane,
    label: 'Travel',
    labelShort: 'Travel',
    color: '#8b5cf6',
    description: 'Agen travel, tour',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Paket', price: 'Harga', customer: 'Pelanggan' },
  },
  RENTAL: {
    key: 'RENTAL',
    icon: Car,
    label: 'Rental',
    labelShort: 'Rental',
    color: '#f59e0b',
    description: 'Rental mobil, motor',
    group: 'TRAVEL_HIBURAN',
    features: { stock: true, debt: true, booking: true, tracking: true, membership: false, cashier: true },
    labels: { product: 'Unit', price: 'Harga', customer: 'Pelanggan' },
  },
  KOLAM_RENANG: {
    key: 'KOLAM_RENANG',
    icon: Waves,
    label: 'Kolam Renang',
    labelShort: 'Kolam Renang',
    color: '#0ea5e9',
    description: 'Kolam renang umum',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: false, tracking: false, membership: true, cashier: true },
    labels: { product: 'Tiket', price: 'Harga', customer: 'Pengunjung' },
  },
  GYM: {
    key: 'GYM',
    icon: Dumbbell,
    label: 'Gym & Fitness',
    labelShort: 'Gym',
    color: '#059669',
    description: 'Tempat gym, fitness center',
    group: 'TRAVEL_HIBURAN',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Paket', price: 'Harga', customer: 'Member' },
  },

  // ========================================
  // 🛍️ BELANJA (12)
  // ========================================
  FASHION: {
    key: 'FASHION',
    icon: ShoppingBag,
    label: 'Fashion',
    labelShort: 'Fashion',
    color: '#ec4899',
    description: 'Toko baju, fashion',
    group: 'BELANJA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  SEPATU: {
    key: 'SEPATU',
    icon: ShoppingBag,
    label: 'Sepatu',
    labelShort: 'Sepatu',
    color: '#374151',
    description: 'Toko sepatu, sandal',
    group: 'BELANJA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  TAS: {
    key: 'TAS',
    icon: ShoppingBag,
    label: 'Tas',
    labelShort: 'Tas',
    color: '#92400e',
    description: 'Toko tas, dompet',
    group: 'BELANJA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  GADGET: {
    key: 'GADGET',
    icon: Package,
    label: 'Gadget',
    labelShort: 'Gadget',
    color: '#3b82f6',
    description: 'Toko HP, gadget, aksesoris',
    group: 'BELANJA',
    features: { stock: true, debt: true, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  KELONTONG: {
    key: 'KELONTONG',
    icon: ShoppingCart,
    label: 'Kelontong',
    labelShort: 'Kelontong',
    color: '#10b981',
    description: 'Warung kelontong, sembako',
    group: 'BELANJA',
    features: { stock: true, debt: true, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  MINIMARKET: {
    key: 'MINIMARKET',
    icon: Store,
    label: 'Minimarket',
    labelShort: 'Minimarket',
    color: '#16a34a',
    description: 'Minimarket, toko retail',
    group: 'BELANJA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  BANGUNAN: {
    key: 'BANGUNAN',
    icon: Hammer,
    label: 'Toko Bangunan',
    labelShort: 'Bangunan',
    color: '#f59e0b',
    description: 'Material bangunan, alat tukang',
    group: 'BELANJA',
    features: { stock: true, debt: true, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Material', price: 'Harga', customer: 'Kontraktor' },
  },
  KOSMETIK: {
    key: 'KOSMETIK',
    icon: Sparkles,
    label: 'Kosmetik',
    labelShort: 'Kosmetik',
    color: '#db2777',
    description: 'Toko kosmetik, makeup',
    group: 'BELANJA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  PERHIASAN: {
    key: 'PERHIASAN',
    icon: Sparkles,
    label: 'Perhiasan',
    labelShort: 'Perhiasan',
    color: '#fbbf24',
    description: 'Toko emas, perhiasan',
    group: 'BELANJA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  MAINAN: {
    key: 'MAINAN',
    icon: PartyPopper,
    label: 'Mainan',
    labelShort: 'Mainan',
    color: '#f97316',
    description: 'Toko mainan anak',
    group: 'BELANJA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  OLAHRAGA: {
    key: 'OLAHRAGA',
    icon: Dumbbell,
    label: 'Olahraga',
    labelShort: 'Olahraga',
    color: '#059669',
    description: 'Toko alat olahraga',
    group: 'BELANJA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  PASAR: {
    key: 'PASAR',
    icon: Store,
    label: 'Pasar',
    labelShort: 'Pasar',
    color: '#10b981',
    description: 'Pasar tradisional',
    group: 'BELANJA',
    features: { stock: true, debt: true, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },

  // ========================================
  // 📦 LAINNYA (14)
  // ========================================
  LAUNDRY: {
    key: 'LAUNDRY',
    icon: Shirt,
    label: 'Laundry',
    labelShort: 'Laundry',
    color: '#3b82f6',
    description: 'Cuci kiloan, cuci satuan, setrika',
    group: 'LAINNYA',
    features: { stock: false, debt: false, booking: false, tracking: true, membership: false, cashier: true },
    labels: { product: 'Layanan', price: 'Harga', customer: 'Pelanggan' },
  },
  DRY_CLEAN: {
    key: 'DRY_CLEAN',
    icon: Shirt,
    label: 'Dry Clean',
    labelShort: 'Dry Clean',
    color: '#06b6d4',
    description: 'Laundry dry clean',
    group: 'LAINNYA',
    features: { stock: false, debt: false, booking: false, tracking: true, membership: false, cashier: true },
    labels: { product: 'Layanan', price: 'Harga', customer: 'Pelanggan' },
  },
  TAILOR: {
    key: 'TAILOR',
    icon: Scissors,
    label: 'Tailor',
    labelShort: 'Tailor',
    color: '#8b5cf6',
    description: 'Jahit baju, penjahit',
    group: 'LAINNYA',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Harga', customer: 'Pelanggan' },
  },
  THRIFT_SHOP: {
    key: 'THRIFT_SHOP',
    icon: ShoppingBag,
    label: 'Thrift Shop',
    labelShort: 'Thrift',
    color: '#92400e',
    description: 'Toko baju bekas, thrift',
    group: 'LAINNYA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pelanggan' },
  },
  KOST: {
    key: 'KOST',
    icon: Home,
    label: 'Kost & Kontrakan',
    labelShort: 'Kost',
    color: '#0891b2',
    description: 'Kost, kontrakan, sewa kamar',
    group: 'LAINNYA',
    features: { stock: false, debt: true, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Kamar', price: 'Harga', customer: 'Penghuni' },
  },
  JASA_ANGKUT: {
    key: 'JASA_ANGKUT',
    icon: Truck,
    label: 'Jasa Angkut',
    labelShort: 'Angkut',
    color: '#f59e0b',
    description: 'Jasa angkut barang',
    group: 'LAINNYA',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Pelanggan' },
  },
  YOGA: {
    key: 'YOGA',
    icon: Heart,
    label: 'Yoga',
    labelShort: 'Yoga',
    color: '#a855f7',
    description: 'Studio yoga, senam',
    group: 'LAINNYA',
    features: { stock: false, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Kelas', price: 'Harga', customer: 'Member' },
  },
  PETSHOP: {
    key: 'PETSHOP',
    icon: Dog,
    label: 'Pet Shop',
    labelShort: 'Pet Shop',
    color: '#f97316',
    description: 'Makanan hewan, grooming, aksesoris',
    group: 'LAINNYA',
    features: { stock: true, debt: false, booking: true, tracking: false, membership: true, cashier: true },
    labels: { product: 'Produk', price: 'Harga', customer: 'Pet Owner' },
  },
  PET_GROOMING: {
    key: 'PET_GROOMING',
    icon: Sparkles,
    label: 'Pet Grooming',
    labelShort: 'Grooming',
    color: '#ea580c',
    description: 'Grooming hewan peliharaan',
    group: 'LAINNYA',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: true },
    labels: { product: 'Layanan', price: 'Harga', customer: 'Pet Owner' },
  },
  BANK: {
    key: 'BANK',
    icon: Store,
    label: 'Bank',
    labelShort: 'Bank',
    color: '#3b82f6',
    description: 'Bank, ATM',
    group: 'LAINNYA',
    features: { stock: false, debt: false, booking: false, tracking: false, membership: false, cashier: false },
    labels: { product: 'Layanan', price: '-', customer: 'Nasabah' },
  },
  PROPERTI: {
    key: 'PROPERTI',
    icon: Home,
    label: 'Properti',
    labelShort: 'Properti',
    color: '#0891b2',
    description: 'Agen properti, rumah, tanah',
    group: 'LAINNYA',
    features: { stock: true, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Listing', price: 'Harga', customer: 'Klien' },
  },
  NOTARIS: {
    key: 'NOTARIS',
    icon: BookOpen,
    label: 'Notaris',
    labelShort: 'Notaris',
    color: '#6b7280',
    description: 'Notaris, PPAT',
    group: 'LAINNYA',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: false, cashier: false },
    labels: { product: 'Layanan', price: 'Tarif', customer: 'Klien' },
  },
  FOTOCOPY: {
    key: 'FOTOCOPY',
    icon: Printer,
    label: 'Fotocopy',
    labelShort: 'Fotocopy',
    color: '#4f46e5',
    description: 'Fotocopy, print, scan',
    group: 'LAINNYA',
    features: { stock: true, debt: false, booking: false, tracking: false, membership: false, cashier: true },
    labels: { product: 'Layanan', price: 'Harga', customer: 'Pelanggan' },
  },
  KURSUS: {
    key: 'KURSUS',
    icon: School,
    label: 'Kursus',
    labelShort: 'Kursus',
    color: '#8b5cf6',
    description: 'Tempat kursus, bimbel, les',
    group: 'LAINNYA',
    features: { stock: false, debt: false, booking: true, tracking: true, membership: true, cashier: true },
    labels: { product: 'Paket', price: 'Harga', customer: 'Siswa' },
  },
};

// ==========================================
// HELPER FUNCTIONS
// ==========================================

/**
 * Get category config by key
 */
export function getCategoryConfig(category: string): CategoryConfig | null {
  return CATEGORY_CONFIG[category] || null;
}

/**
 * Get all categories as array
 */
export function getCategoryList(): CategoryConfig[] {
  return Object.values(CATEGORY_CONFIG);
}

/**
 * Get categories by group
 */
export function getCategoriesByGroup(groupKey: string): CategoryConfig[] {
  return Object.values(CATEGORY_CONFIG).filter(cat => cat.group === groupKey);
}

/**
 * Get all category groups
 */
export function getCategoryGroupList(): CategoryGroup[] {
  return Object.values(CATEGORY_GROUPS);
}

/**
 * Get category options for select
 */
export function getCategoryOptions(): { value: string; label: string }[] {
  return Object.values(CATEGORY_CONFIG).map((cat) => ({
    value: cat.key,
    label: cat.label,
  }));
}

/**
 * Default category config for unknown categories
 */
export const DEFAULT_CATEGORY_CONFIG: CategoryConfig = {
  key: 'OTHER',
  icon: Package,
  label: 'Lainnya',
  labelShort: 'Lainnya',
  color: '#6b7280',
  description: 'Kategori lainnya',
  group: 'LAINNYA',
  features: {
    stock: true,
    debt: false,
    booking: false,
    tracking: false,
    membership: false,
    cashier: true,
  },
  labels: {
    product: 'Produk',
    price: 'Harga',
    customer: 'Pelanggan',
  },
};
